### PR TITLE
Layout files and content holders.

### PR DESCRIPTION
**Pull request by git-akshay**
Files contain 2 fragments,
1. AllNodeFragment
2. NewNodeFragment

and the corresponding layout files.
Its a work under progress.

But its completely unrelated to the project files at this moment so a merge wont hurt. :)

### CODE REVIEW

**Comment by iayanpahwa** [comment]
@git-akshay please pull latest changes and update the PR to solve merge conflicts. PR #37 merged already causing conflicts. @anshulkatta please sync with @git-akshay for same.

**Comment by anshulkatta** [comment]
i already asked him to send me the project ..i can sync and then merge with
the app..

but i m pretty sure he can do it himself....

**Comment by git-akshay** [comment]
Will do as soon as i can.

**Comment by git-akshay** [comment]
Will create a new PR with all files in sync.

**Pull request closed without merging**
